name: Build and Push to GHCR

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/j-sotomayor/holaflask:latest

      - name: Mostrar variables (solo locales, no secretos)
        run: |
          echo "Probando conexion SSH con:"
          echo "Host: ${{ secrets.VPS_HOST }}"
          echo "Usuario: ${{ secrets.VPS_USER }}"
          echo "Puerto: ${{ secrets.VPS_SHH_PORT }}"
          echo "Password: ${{ secrets.VPS_PASSWORD }}"

      - name: Probar la ssh en el vps
        uses: app/deployssh-action@v1
        with: 
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_SHH_PORT }} 
          script: |
           echo "Probando conexion ssh en el vps"
           hostname
           whoami 
           uptime
